### ISSUE TITLE
Build Error with gradle

### ISSUE THREAD

**Issue by Shrey1907** [londonappbrewery/mi_card_flutter#29]
This error is showing .please help!!!!
`Launching lib\main.dart on ONEPLUS A6000 in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by Shrey1907** [comment]
I tried changing the distribution URL in the gradle.properties file but more errors popped up. I have no clue what to do
